# Generated by Django 2.2.3 on 2019-07-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='descricao',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='nome',
            field=models.CharField(max_length=90),
        ),
    ]
