# Generated by Django 2.2.3 on 2019-07-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('qualidade', models.PositiveIntegerField()),
                ('categoria', models.CharField(choices=[('vegano', 'Vegano'), ('vegetariano', 'Vegetariano')], max_length=20)),
                ('nivel_avaliacao', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('foto', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='loja',
            name='foto',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
