# Generated by Django 2.2.3 on 2019-07-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190715_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servico',
            name='servico',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('nutricionista', 'Nutricionista'), ('dicas', 'Dicas'), ('auxilio', 'Auxilio')], default='', max_length=20),
        ),
    ]
