# Generated by Django 2.2.3 on 2019-07-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190711_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=10)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=75)),
                ('celular', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='loja',
            name='preco',
        ),
        migrations.AddField(
            model_name='loja',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='servico',
            name='servico',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('nutricionista', 'Nutricionista'), ('dicas', 'Dicas'), ('auxilio', 'Auxilio')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='loja',
            name='lugar',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='loja',
            name='nome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='texto',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(max_length=50),
        ),
    ]
