# Generated by Django 2.2.3 on 2019-07-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190713_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=40)),
                ('telefone', models.CharField(default='', max_length=15)),
                ('assunto', models.CharField(default='', max_length=50)),
                ('mensagem', models.TextField(default='', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='celular',
            field=models.CharField(max_length=10),
        ),
    ]
