# Generated by Django 2.2.3 on 2019-07-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190713_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='nascimento',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='telefone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contato',
            name='mensagem',
            field=models.TextField(default='', max_length=100),
        ),
    ]
