# Generated by Django 2.2.3 on 2019-07-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190714_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='nascimento',
        ),
    ]
