# Generated by Django 2.2.3 on 2019-07-14 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20190714_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=40)),
                ('telefone', models.CharField(default='', max_length=15)),
                ('assunto', models.CharField(default='', max_length=50)),
                ('mensagem', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.TextField(default='')),
                ('lugar', models.CharField(max_length=50)),
                ('produtos', models.CharField(choices=[('Mc', 'Mercado'), ('Lr', 'Livros'), ('Rp', 'Roupas'), ('Ev', 'Eco-vegan'), ('Ol', 'On-line'), ('Cm', 'Cosmeticos')], max_length=2)),
                ('foto', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.TextField(default='')),
                ('qualidade', models.PositiveIntegerField()),
                ('categoria', models.CharField(choices=[('vegano', 'Vegano'), ('vegetariano', 'Vegetariano')], max_length=20)),
                ('nivel_avaliacao', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('foto', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.TextField(max_length=50)),
                ('foto', models.ImageField(default='', upload_to='')),
                ('servico', models.CharField(choices=[('delivery', 'Delivery'), ('nutricionista', 'Nutricionista'), ('dicas', 'Dicas'), ('auxilio', 'Auxilio')], default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField(default='')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
