# Generated by Django 2.2.3 on 2019-07-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_cadastro_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugar',
            name='created_date',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='nascimento',
            field=models.DateField(default=''),
        ),
    ]
