# Generated by Django 2.2.3 on 2019-07-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190714_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugar',
            name='published_date',
        ),
    ]
