# Generated by Django 2.2.3 on 2019-07-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_lugar_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='nascimento',
            field=models.DateField(default=1969),
        ),
    ]
