# Generated by Django 2.2.3 on 2019-07-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190714_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='nascimento',
        ),
    ]
